<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFyvju0i\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFyvju0i/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFyvju0i.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFyvju0i\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFyvju0i\appProdProjectContainer([
    'container.build_hash' => 'Fyvju0i',
    'container.build_id' => '4d21ba66',
    'container.build_time' => 1669799332,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFyvju0i');
