version: '3.7'

services:
  be_182613_presta:
    image: akademia/be_182613_presta
    environment: 
      - DATABASE_HOST=be_182613_db
      - DATABASE_PORT=3306
      - DATABASE_NAME=prestashop
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
    deploy:
      restart_policy:
      condition: on-failure
      delay: 3s
      max_attempts: 3
      window: 60s
    ports: 
      - 18261:80
      - 18436:443

  be_182613_db: 
    image: akademia/be_182613_db
    environment: 
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=root
      - MARIADB_PASSWORD=root
      - MARIADB_DATABASE=prestashop
    deploy:
      restart_policy:
      condition: on-failure
      delay: 3s
      max_attempts: 3
      window: 60s