<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGrx363P\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGrx363P/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerGrx363P.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerGrx363P\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerGrx363P\appAppKernelProdContainer([
    'container.build_hash' => 'Grx363P',
    'container.build_id' => 'b194aeb3',
    'container.build_time' => 1670054706,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGrx363P');
