<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDdyvbev\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDdyvbev/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDdyvbev.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDdyvbev\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDdyvbev\appProdProjectContainer([
    'container.build_hash' => 'Ddyvbev',
    'container.build_id' => '5e252fb8',
    'container.build_time' => 1669799504,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDdyvbev');
